version: "3.4"
services:
  api:
    image: bw-code-sample-api
    build: api
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    command: dotnet api.dll
  app:
    image: bw-code-sample-app
    build: app
    volumes:
      - type: bind
        source: ./app
        target: /app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn start
