version: "3.4"
services:
  api:
      image: mcr.microsoft.com/dotnet/sdk
      container_name: bw-code-sample-api
      volumes:
        - ./api:/app
      environment:
        NODE_ENV: development
        ASPNETCORE_URLS: http://*:5000
      ports:
        - 5000:5000
      working_dir: /app
      command: dotnet watch run --no-launch-profile
  app:
    image: node:alpine
    container_name: bw-code-sample-app
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    working_dir: /app
    command: yarn start
