version: "3.4"
services:
  api:
    image: bw-code-sample-api
    container_name: bw-code-sample-api
    build: api
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    command: dotnet api.dll
  app:
    image: node:alpine
    container_name: bw-code-sample-app
    volumes:
      - ./app:/app
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    working_dir: '/app'
    command: yarn start
