name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-api:

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: docker build api

  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd app
          yarn install
          yarn build
